### ISSUE TITLE
Version comparaison in migration files contain issues

### ISSUE THREAD

**Issue by Galixte** [Sajaki/RankPostStyling#4]
Hi @Sajaki,

like this issue: https://github.com/Sajaki/QuickStyle/issues/3 migrations files here: https://github.com/Sajaki/RankPostStyling/tree/develop32/migrations contain ```rt_version``` instead of ```rps_version``` in comparaison step.

Am I mistaken?

I’ve submitted a PR to fix that: https://github.com/Sajaki/RankPostStyling/pull/5.

Regards.

**Comment by Sajaki** [comment]
yes, it's probably wrong, due to a copy paste from recenttopics.
